version: "3.2"
services:
  auth-server:
    image: php:apache
    volumes:
      - ./auth-server:/var/www/html
    working_dir: /var/www/html
    ports:
      - 127.0.0.1:8099:80

  auth-client:
    build: ./auth-client
    volumes:
      - ./auth-client:/var/www/html
    working_dir: /var/www/html
    ports:
      - 127.0.0.1:8098:80